### ISSUE TITLE
Unknown values considered as missing

### ISSUE THREAD

**Issue by airon90** [Ambrosiani/museums-wikidata#1]
Museums with "unknown value" (in Swedish "okänt värde"), e.g. unknown number of visitors/year,  should be considered like musems that don't have those data.

In fact, go here: https://steko.github.io/museums-wikidata/
Go to Milan (it is in the Northern central part of Italy) and you'll see only one green dot. It's the latest museum I inserted and I set "visitors" as "unknown value". If you check the data of the dot you see that "Visitors" (I know that the sentences should be translated. I already file a PR) is shown and set to "t268481479".

**Comment by Ambrosiani** [comment]
Yes, I see what you mean. I'll rewrite the if clause later today.

**Comment by Ambrosiani** [comment]
fixed it by checking the type parameter. Needs to be uri for web site, literal for visitor count.

**Comment by airon90** [comment]
Good! Thank you :)
