### ISSUE TITLE
Don't show unknown values

### ISSUE THREAD

**Issue by airon90** [Ambrosiani/museums-wikidata#2]
By #1 you fixed the count of unknown values as known values. However you still print unknown values as data. 

Again, go here: https://steko.github.io/museums-wikidata/
Go to Milan (it is in the Northern central part of Italy) and you'll see only one green dot. It's the latest museum I inserted and I set "visitors" as "unknown value". If you check the data of the dot you see that "Visitors" (I know that the sentences should be translated. I already file a PR) is shown and set to "t268481479".

**Comment by Ambrosiani** [comment]
Yes, I thought it would be good to show the bad data, to remind people about updating!

**Comment by airon90** [comment]
Ok, but I think it's good to show a message like "Unknown value" instead of "t268481479" ;)
(I'd help you but I'm not a coder :/)

**Comment by Ambrosiani** [comment]
Sounds reasonable!

**Comment by Ambrosiani** [comment]
done.

**Comment by airon90** [comment]
Thank you very much!
