### ISSUE TITLE
Auto-pan map to country

### ISSUE THREAD

**Issue by steko** [Ambrosiani/museums-wikidata#3]
Currently, when selecting a country, the map doesn't pan to the country.

Perhaps this can be done with [`panInsideBounds`](http://leafletjs.com/reference.html#map-paninsidebounds) passing the maximum and minimum values for latitude and longitude respectively?

**Comment by Ambrosiani** [comment]
Yes, sounds like the way to do it. I'm on a skiing vacation but will give it a try sometime next week.

**Comment by Ambrosiani** [comment]
done (sort of). Only a few countries in Wikidata have bounds (properties P1332–1335), so I only used P625 coordinate location.
